# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- develop

pool: h6srmbdnre9-agent-pool

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  displayName: NuGet Tool Installer

- task: NuGetCommand@2
  displayName: Restore solution
  inputs:
    restoreSolution: '$(solution)'

# Build project
- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'build'
    arguments: '--no-restore'

# - task: VSTest@2
#   displayName: Run tests
#   inputs:
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'
    
# - task: PublishTestResults@2
#   displayName: Publish test results to Azure
#   inputs:
#     testResultsFormat: 'XUnit'
#     testResultsFiles: '**/TEST-*.xml'
#     testRunTitle: 'Integration Tests'

- task: PublishBuildArtifacts@1
  displayName: Publish to Azure
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'