# appsettings.yml
Logging:
    LogLevel: 
      Default: Information
      Microsoft.AspNetCore: Information

AllowedHosts: "*"

ConnectionStrings:
  AzureSqlAuth: <secret SQL connection string here>
Jwt:
  Issuer: test-user@live.com
  Audience: test-user@live.com
  Key: ijurkbdlhmklqacwqzdxmkkhvqowlyqaijurkbdlhmklqacwqzdxmkkhvqowlyqa